plugin:
  debug: false
  language: en

database:
  type: "sqlite"

  mysql:
    host: "localhost"
    port: "3306"
    database: "minecraft"
    user: "root"
    password: "password"
    pool-size: 10
    minimum-idle: 5
    idle-timeout: 600000
    connection-timeout: 30000
    max-lifetime: 1800000

  sqlite:
    file: "database.sqlite"